import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./ClientLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative antialiased">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
